name: CI - QR Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start server in background
        run: |
          python appV2.py &  # Lance le serveur en arrière-plan
          sleep 5  # Attend que le serveur soit prêt

      - name: Run tests
        run: |
          python test_sql.py
