name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start Flask server
      run: |
        # Lance le serveur en arrière-plan avec le bon host
        python appV2.py --host 0.0.0.0 --port 5000 &
        # Attend 5 secondes que le serveur démarre
        sleep 5
        # Vérifie que le serveur est bien démarré
        curl -s http://localhost:5000/health || echo "Server not ready"
    
    - name: Run tests
      run: |
        python test_sql.py