name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Si vous utilisez pytest
        
    - name: Start server and run tests
      run: |
        # Lance le serveur en arrière-plan avec logging
        python votre_serveur.py > server.log 2>&1 &
        
        # Attend que le serveur soit prêt (version améliorée)
        for i in {1..10}; do
          if curl -s http://localhost:5000/health >/dev/null; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server... (attempt $i/10)"
          sleep 3
        done
        
        # Affiche les logs du serveur pour debug
        cat server.log
        
        # Exécute les tests
        python test_sql.py || exit 1
        
        # Tue le processus serveur
        pkill -f "python votre_serveur.py"