name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libzbar0  # Installation de la dépendance système pour pyzbar
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start server and verify
      run: |
        # Démarrer le serveur en arrière-plan avec logging
        python appV2.py > server.log 2>&1 &
        
        # Vérification que le serveur est prêt
        echo "Waiting for server to start..."
        sleep 5
        if ! curl -s http://localhost:5000/health; then
          echo "Server failed to start. Logs:"
          cat server.log
          exit 1
        fi
        
    - name: Run tests
      run: |
        python test_sql.py